# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Hashibutogarasu.FirewallConsoleApp
PackageVersion: 1.1.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fwall.exe
  PortableCommandAlias: FirewallConsoleApp
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Hashibutogarasu/FirewallConsoleApp/releases/download/v1.1.3/fwall.zip
  InstallerSha256: 3C52DAEACF3DEF883CAAE72F4317800D0CB9CE5ADD0E2119D68B23D9E62551B0
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-02-12
