name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build-and-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: windows-latest
    steps:
      - name: Checkout FirewallConsoleApp
        uses: actions/checkout@v4
        with:
          path: FirewallConsoleApp

      - name: Checkout LibFirewall
        uses: actions/checkout@v4
        with:
          repository: Hashibutogarasu/LibFirewall
          path: LibFirewall
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout LibFirewallShared
        uses: actions/checkout@v4
        with:
          repository: Hashibutogarasu/LibFirewallShared
          path: LibFirewallShared
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout FirewallConsoleAppAPI
        uses: actions/checkout@v4
        with:
          repository: Hashibutogarasu/FirewallConsoleAppAPI
          path: FirewallConsoleAppAPI
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build and Pack Dependencies
        run: |
          dotnet pack LibFirewall.Shared/LibFirewall.Shared.csproj -c Release -o ./local-packages
          dotnet pack LibFirewall/LibFirewall.csproj -c Release -o ./local-packages

      - name: Publish Single File
        run: dotnet publish FirewallConsoleApp/FirewallConsoleApp.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish -s ./local-packages -s https://api.nuget.org/v3/index.json

      - name: Zip Artifact
        run: Compress-Archive -Path ./publish/* -DestinationPath ./FirewallConsoleApp.zip

      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} ./FirewallConsoleApp.zip --clobber

      - name: Publish to Winget
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: FirewallConsoleApp
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ needs.release-please.outputs.tag_name }}
